---
$schema: https://json-schema.org/draft/2020-12/schema
title: definitions a Facility location, type schema:Place
type: object
properties:
  '@id':
    type: string
  '@type':
    const: schema:Place
  'schema:additionalType':
    type: array
    items:
      type: string
    contains:
      const: xas:Facility
    minItems: 1
  'schema:identifier':
    anyOf:
    - type: string
    - $ref: '#/$defs/Identifier'
  'schema:name':
    type: string
  'schema:additionalProperty':
    type: array
    items:
      $ref: '#/$defs/AdditionalProperty'
required:
- '@type'
- 'schema:additionalType'
- 'schema:name'
$defs:
  AdditionalProperty:
    $ref: ../../schemaorgProperties/additionalProperty/schema.yaml
  Identifier:
    $ref: ../../schemaorgProperties/identifier/schema.yaml