$schema: https://json-schema.org/draft/2020-12/schema
title: ADA RAMAN Product Profile
description: >-
  Technique-specific profile for Raman Spectroscopy (RAMAN) products.
  Extends the base ADA product profile with constraints on valid RAMAN component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a RAMAN product type identifier.
        contains:
          enum:
            - "ada:RAMANRawTabular"
            - "Raman vibrational spectroscopy"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:RAMANRawTabular"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
