$schema: https://json-schema.org/draft/2020-12/schema
title: Has Part File Type
description: >-
  Files within an archive package (hasPart). Uses CDIF 2026 distribution patterns
  with DDI-CDI types. The @type must NOT contain schema:DataDownload (distinguishing
  hasPart files from top-level distribution files). File-type details are merged
  via allOf rather than nested in fileDetail.
allOf:
  - type: object
    properties:
      "@id":
        type: string
      "@type":
        type: array
        items:
          type: string
        not:
          contains:
            const: "schema:DataDownload"
        minItems: 1
      "schema:additionalType":
        type: array
        description: The dataComponentType or supDocType
        items:
          type: string
      "schema:name":
        type: string
        description: String name of file, must be unique within the containing package
      "schema:description":
        type: string
      "spdx:checksum":
        type: object
        properties:
          "spdx:algorithm":
            type: string
          "spdx:checksumValue":
            type: string
      "schema:size":
        type: object
        properties:
          "@type":
            const: "schema:QuantitativeValue"
          "schema:value":
            type: integer
          "schema:unitText":
            type: string
            default: byte
      "schema:encodingFormat":
        type: array
        items:
          type: string
  - anyOf:
      - $ref: ../image/schema.yaml
      - $ref: ../imageMap/schema.yaml
      - $ref: ../tabularData/schema.yaml
      - $ref: ../collection/schema.yaml
      - $ref: ../dataCube/schema.yaml
      - $ref: ../document/schema.yaml
      - $ref: ../supDocImage/schema.yaml
      - $ref: ../otherFile/schema.yaml
      - type: object
        properties:
          "@type":
            const:
              - "Metadata"
        required:
          - "@type"
