$schema: https://json-schema.org/draft/2020-12/schema
title: ADA ARGT Product Profile
description: >-
  Technique-specific profile for Argon Geochronology and Thermochronology (ARGT) products.
  Extends the base ADA product profile with constraints on valid ARGT component
  types and detailARGT requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a ARGT product type identifier.
        contains:
          enum:
            - "40Ar/39Ar Geochronology and Thermochronology (ARGT)"
            - "40Ar/39Ar geochronology and thermochronology"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:ARGTDocument"
                          - "ada:ARGTCollection"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
