---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: 'Optional properties for CDIF discovery metadata schema, with schema: prefixes'
description: Building block specifies properties for CDIF schama.org discovery record
properties:
  'schema:description':
    type: string
    description: A short summary describing a dataset. This text will be indexed by search applications,
      so the more information here, the better.
  'schema:additionalType':
    description: identifiers for datatypes from other vocabularies (not schema.org) that apply to this
      metadata.
    type: array
    minItems: 0
    items:
      anyOf:
      - type: string
      - $ref: '#/$defs/DefinedTerm'
  'schema:sameAs':
    description: The other identifiers for the dataset. Schema.org has three ways of encoding identifiers--
      a text description, a URL, or by using the schema:PropertyValue field. The Science on Schema.org
      guidance strongly recommends using the PropertyValue approach. see https://github.com/ESIPFed/science-on-schema.org   ....
      Dataset.md#identifier.
    type: array
    minItems: 0
    items:
      anyOf:
      - $ref: '#/$defs/Identifier'
      - type: string
  'schema:version':
    type:
    - string
    - number
    description: The version number or identifier for this dataset (text or numeric). The values should
      sort from oldest to newest using an alphanumeric sort on version strings
  'schema:inLanguage':
    type: string
    description: the language of the dataset content
  'schema:datePublished':
    type: string
    description: ISO8601 formatted date (and optional time if relevant) when Dataset was made public.
  'schema:relatedLink':
    type: array
    description: links to related resources; linkRelationship specifies how the resource is related.
    items:
      type: object
      properties:
        '@type':
          type: string
          const: schema:LinkRole
        'schema:linkRelationship':
          anyOf:
          - $ref: '#/$defs/DefinedTerm'
          - type: string
        target:
          type: object
          properties:
            '@type':
              type: string
              const: schema:EntryPoint
            'schema:encodingFormat':
              type: string
              description: registered MIME types are expected
            'schema:name':
              type: string
            'schema:url':
              type: string
              format: uri
  'schema:publishingPrinciples':
    description: FDOF digitalObjectMutability, RDA digitalObjectPolicy, FDOF PersistencyPolicy. Policies
      related to maintenance, update, expected time to live. If an online resource documents the policies
      or a URI is used to identify the conditions, recommend using schema:CreativeWork to provide a label
      (name) and an identifier (URI or URL).
    type: array
    minItems: 0
    items:
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: a reference to a publishing principles statement
      - $ref: '#/$defs/LabeledLink'
  'schema:keywords':
    description: Keywords are an array of strings, an array of schema:DefinedTerms, or some combination
      of these. If you have information about a controlled vocabulary from which keywords come from, use
      schema:DefinedTerm to descibe that keyword. This allowed variability makes parsing metadata hard;
      recommend using DefinedTerm for all keywords if any of them are from a known vocabulary, otherwise
      an array of strings.
    type: array
    items:
      anyOf:
      - $ref: '#/$defs/DefinedTerm'
      - type: string
  'schema:creator':
    description: author or orginator of intellectual content of dataset. Uset the JSON-LD @list construct
      to preserve author order. Use contributor with the Role property to specify other roles related
      to creation or stewardship of the resource.
    type: object
    properties:
      '@list':
        type: array
        items:
          anyOf:
          - type: object
            properties:
              '@id':
                type: string
                description: a identifier for an agent defined in this metadata, or externally; must be
                  dereferenceable
          - $ref: '#/$defs/Person'
          - $ref: '#/$defs/Organization'
  'schema:contributor':
    description: other parties who played a role in production of dataset
    type: array
    items:
      anyOf:
      - type: object
        properties:
          '@id':
            type: string
            description: a identifier for an agent defined in this metadata, or externally; must be dereferenceable
      - $ref: '#/$defs/Person'
      - $ref: '#/$defs/Organization'
      - $ref: '#/$defs/Contributor'
  'schema:publisher':
    description: Party who made the dataset publicly available
    anyOf:
    - type: object
      properties:
        '@id':
          type: string
          description: a identifier for an agent defined in this metadata, or externally; must be dereferenceable
    - $ref: '#/$defs/Person'
    - $ref: '#/$defs/Organization'
  'schema:provider':
    description: Party who maintains the distribution options for the dataset. If there are multiple distributions
      from different providers, use the provider property on distribution/DataDownload
    type: array
    items:
      anyOf:
      - type: object
        properties:
          '@id':
            type: string
            description: a identifier for an agent defined in this metadata, or externally; must be dereferenceable
      - $ref: '#/$defs/Person'
      - $ref: '#/$defs/Organization'
  'schema:funding':
    type: array
    items:
      $ref: '#/$defs/Funder'
  'schema:variableMeasured':
    description: What does the dataset measure? (e.g., temperature, pressure)
    type: array
    items:
      $ref: '#/$defs/VariableMeasured'
  'schema:spatialCoverage':
    description: To specify location that is the subject of resource content; use schema.org place names,
      bounding box, point or optional OGC WKT gemetry.
    type: array
    items:
      $ref: '#/$defs/SpatialExtent'
  'schema:temporalCoverage':
    description: The time interval during which data was collected or observations were made; or a time
      period that an activity or collection is linked to intellectually or thematically (for example,
      1997 to 1998; the 18th century) (see https://documentation.ardc.edu.au/display/DOC/Temporal+coverage).
      For documentation of Earth Science, Paleobiology or Paleontology datasets, we are interested in
      the second case-- the time period that data are linked to thematically..
    type: array
    items:
      $ref: '#/$defs/TemporalExtent'
$defs:
  LabeledLink:
    $ref: ../labeledLink/schema.yaml
  Identifier:
    $ref: ../identifier/schema.yaml
  DefinedTerm:
    $ref: ../definedTerm/schema.yaml
  Person:
    $ref: ../person/schema.yaml
  Organization:
    $ref: ../organization/schema.yaml
  Contributor:
    $ref: ../agentInRole/schema.yaml
  Funder:
    $ref: ../funder/schema.yaml
  VariableMeasured:
    $ref: ../variableMeasured/schema.yaml
  SpatialExtent:
    $ref: ../spatialExtent/schema.yaml
  TemporalExtent:
    $ref: ../temporalExtent/schema.yaml
