$schema: https://json-schema.org/draft/2020-12/schema
title: ADA DSC Product Profile
description: >-
  Technique-specific profile for Differential Scanning Calorimetry (DSC) products.
  Extends the base ADA product profile with constraints on valid DSC component
  types and detailDSC requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a DSC product type identifier.
        contains:
          enum:
            - "ada:DSCHeatTabular"
            - "ada:DSCResultsTabular"
            - "Differential Scanning Calorimetry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:DSCHeatTabular"
                          - "ada:DSCResultsTabular"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:calibrationFile"
