$schema: https://json-schema.org/draft/2020-12/schema
title: ADA DSC Product Profile
description: >-
  Technique-specific profile for Differential Scanning Calorimetry (DSC) products.
  Extends the base ADA product profile with constraints on valid DSC component
  types and detailDSC requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a DSC product type identifier.
        contains:
          enum:
            - "Differential Scanning Calorimetry (DSC)"
            - "Differential Scanning Calorimetry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:DSCHeatTabular"
                          - "ada:DSCResultsTabular"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
