$schema: https://json-schema.org/draft/2020-12/schema
title: ADA PSFD Product Profile
description: >-
  Technique-specific profile for Particle Size-Frequency Distribution (PSFD) products.
  Extends the base ADA product profile with constraints on valid PSFD component
  types and detailPSFD requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a PSFD product type identifier.
        contains:
          enum:
            - "ada:PSFDTabular"
            - "Particle Size Frequency Distribution"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:PSFDTabular"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:calibrationFile"
