---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: 'CDIF discovery metadata schema, with schema: prefixes'
description: 'JSON schema for JSON-LD documents that describe science datasets for the CDIF DataDiscovery
  profile. See https://cdif.codata.org/, USING OGC building blocks modularization.  Content based on Google
  guide for publishers (https://developers.google.com/search/docs/data-types/dataset), and the Earth Science
  Information Partners (ESIP) Science on Schema.org recommendations v1.3 prerelease (see https://doi.org/10.5281/zenodo.2628755
  dataset.md for current recommendations document). The context is not specified in the schema, but must
  be added in instance documents. ''"@context": {"schema":"https://schema.org/", "dcterms": "http://purl.org/dc/terms/",
  "geosparql": "http://www.opengis.net/ont/geosparql#", "spdx": "http://spdx.org/rdf/terms#" }'' 2024-07-24,
  SMR change handling of registration information to align with current proposal for cross-domain interoperability
  (CDIF). Created by Stephen Richard 2024-07-30 based on NSF GeoCODES dataset and iSamples draft2 schema.org
  JSON schema. NOTE-- assumes that schema:https://schema.org is declared in context, so schema: namespace
  prefix is required as prefix for all schema.org elements.2025-07-24.  SMR 2025-10-23 update schemaversion
  to https://json-schema.org/draft/2020-12/schema; add additionalType on organization with the alt schema.org
  types as one option, additional required constraints in various places; update constraint on @type to
  require schema:Dataset. Implement using OGC buildign blocks approach. '
allOf:
- $ref: ../../properties/cdifMandatory/schema.yaml
- $ref: ../../properties/cdifOptional/schema.yaml