$schema: https://json-schema.org/draft/2020-12/schema
$id: https://w3id.org/adaJSONLD/schema/3.0
title: Astromat Archive Product Metadata
description: >-
  Schema for JSON metadata documenting products in Astromat Data Archive (ADA).
  Each project consists of one or more data files and 0 to many supplemental files.
  Each file MUST have an associated YAML metadata file, with the same name,
  but '.yaml' as the file extension. Version 3.0 aligned with CDIF 2026 schema
  for DDI-CDI variable types and CSVW tabular data properties.
type: object
allOf:
  - $ref: ../../cdifProperties/cdifMandatory/schema.yaml
  - $ref: ../../cdifProperties/cdifOptional/schema.yaml
  - type: object
    properties:
      "@type":
        type: array
        items:
          type: string
        allOf:
          - contains:
              const: "schema:Dataset"
          - contains:
              const: "schema:Product"
      "schema:additionalType":
        type: array
        description: >-
          Should have the ada product type and 'ada:DataDeliveryPackage'
        items:
          type: string
        minItems: 1
      submissionType:
        type: string
      "schema:license":
        description: Legal statement of conditions for use and access
        type: array
        minItems: 0
        items:
          anyOf:
            - type: string
            - $ref: ../../adaProperties/creativeWork/schema.yaml
      "schema:relatedLink":
        type: array
        description: Links to related resources at the product level
        items:
          type: object
          properties:
            "@type":
              type: string
              const: "schema:LinkRole"
            "schema:linkRelationship":
              type: string
            "schema:target":
              type: object
              properties:
                "@type":
                  type: string
                  const: "schema:EntryPoint"
                "schema:encodingFormat":
                  type: string
                "schema:name":
                  type: string
                "schema:url":
                  type: string
      "schema:creativeWorkStatus":
        type: string
      "schema:measurementTechnique":
        type: object
        description: Text description of the measurement method
        properties:
          "@type":
            const: "schema:DefinedTerm"
          "schema:name":
            type: string
          "schema:identifier":
            type: string
      "prov:wasGeneratedBy":
        type: array
        description: Analysis events that generated this product
        items:
          type: object
          properties:
            "@type":
              description: >-
                Include 'prov:Activity' and 'schema:Event'
              type: array
              items:
                type: string
              allOf:
                - contains:
                    const: "prov:Activity"
                - contains:
                    const: "schema:Event"
            "prov:used":
              type: array
              description: Instruments used in the analysis
              items:
                $ref: ../../adaProperties/instrument/schema.yaml
            "schema:location":
              $ref: ../../adaProperties/laboratory/schema.yaml
            "schema:mainEntity":
              type: array
              description: Samples analyzed
              items:
                type: object
                properties:
                  "@type":
                    const:
                      - "schema:Thing"
                      - "https://w3id.org/isample/vocabulary/materialsampleobjecttype/materialsample"
                  "schema:additionalType":
                    type: array
                    items:
                      type: string
                  "schema:identifier":
                    type: array
                    items:
                      type: string
            "schema:identifier":
              description: Identifier for the analysis event (sessionID)
              type: string
            "schema:startDate":
              type: string
          required:
            - "prov:used"
      "schema:variableMeasured":
        description: >-
          What does the dataset measure? Define the variables here at the conceptual
          level; the physical implementation details are in the data structure.
          Requires dual typing with schema:PropertyValue and cdi:InstanceVariable
          per CDIF 2026.
        type: array
        items:
          type: object
          properties:
            "@id":
              type: string
              description: >-
                Identifier for this variable, used to link from physical mappings
                in distributions.
            "@type":
              type: array
              items:
                type: string
                enum:
                  - "schema:PropertyValue"
                  - "cdi:InstanceVariable"
              minItems: 2
            "schema:description":
              type: string
              minLength: 10
            "schema:name":
              description: The name as it typically appears in a dataset
              type: string
            "schema:alternateName":
              type: array
              items:
                type: string
                description: Human intelligible name for variable that conveys semantics
            "schema:propertyID":
              description: Ideally a resolvable URI for a property concept
              type: array
              items:
                anyOf:
                  - type: string
                  - type: object
                    properties:
                      "@id":
                        type: string
                  - type: object
                    properties:
                      "@type":
                        type: string
                        const: "schema:DefinedTerm"
                      "schema:name":
                        type: string
                      "schema:identifier":
                        type: object
                      "schema:inDefinedTermSet":
                        type: string
                      "schema:termCode":
                        type: string
                    required:
                      - "@type"
                      - "schema:name"
            "schema:measurementTechnique":
              anyOf:
                - type: string
                - type: object
                  properties:
                    "@id":
                      type: string
                - type: object
                  properties:
                    "@type":
                      type: string
                      const: "schema:DefinedTerm"
                    "schema:name":
                      type: string
                  required:
                    - "@type"
                    - "schema:name"
            "schema:unitText":
              type: string
            "schema:unitCode":
              anyOf:
                - type: string
                - type: object
                  properties:
                    "@id":
                      type: string
                - type: object
                  properties:
                    "@type":
                      type: string
                      const: "schema:DefinedTerm"
                    "schema:name":
                      type: string
                  required:
                    - "@type"
                    - "schema:name"
            "schema:minValue":
              type: number
            "schema:maxValue":
              type: number
            "schema:url":
              type: string
              format: uri
            "cdi:intendedDataType":
              type: string
            "cdi:role":
              type: string
              description: >-
                The role of the variable: MeasureComponent, AttributeComponent,
                DimensionComponent, IdentifierComponent.
            "cdi:describedUnitOfMeasure":
              type: object
              properties:
                "@type":
                  type: string
                  const: "schema:DefinedTerm"
                "schema:name":
                  type: string
              required:
                - "@type"
                - "schema:name"
            "cdi:simpleUnitOfMeasure":
              type: string
            "cdi:uses":
              type: array
              items:
                anyOf:
                  - type: string
                  - type: object
                    properties:
                      "@id":
                        type: string
                  - type: object
                    properties:
                      "@type":
                        type: string
                        const: "schema:DefinedTerm"
                      "schema:name":
                        type: string
                    required:
                      - "@type"
                      - "schema:name"
          required:
            - "@id"
            - "@type"
            - "schema:description"
            - "schema:name"
      "schema:distribution":
        type: array
        description: >-
          Access options for the dataset. Each distribution item is expected to be
          a single file or an archive containing multiple files described in hasPart.
        items:
          anyOf:
            - $ref: ../../adaProperties/files/schema.yaml
            - allOf:
                - $ref: ../../adaProperties/files/schema.yaml
                - type: object
                  description: Archive file with parts.
                  properties:
                    "@type":
                        contains:
                          const: "schema:DataDownload"
                    "schema:hasPart":
                      type: array
                      description: >-
                        Array describing the files in the zip archive.
                      items:
                        allOf:
                          - $ref: ../../adaProperties/files/schema.yaml
                          - type: object
                            properties:
                             "schema:contentURL": false
                             "@type":
                                description: add MediaObject as type for ROCrate compatibility; this file is part of an archive, not independently accessible
                                contains:
                                  const: "schema:MediaObject"
                                not:
                                  contains:
                                    const: "schema:DataDownload"
            - allOf:
              - $ref: ../../schemaorgProperties/webAPI/schema.yaml
              - type: object
                description: >-
                  use cdif schema.org Web API distribution with file result. this profile adds some properties
                properties:
                  "schema:name":
                    type: string
                  "schema:description":
                    type: string
                  "schema:result":
                    description: >-
                      The file(s) that result from invoking this API. Reuses the
                      same single-file or archive-with-hasPart structure.
                    oneOf:
                      - $ref: ../../adaProperties/files/schema.yaml
                      - allOf:
                          - $ref: ../../adaProperties/files/schema.yaml
                          - type: object
                            description: Archive file result with parts.
                            properties:
                              "schema:hasPart":
                                type: array
                                description: Files within the archive result.
                                items:
                                  allOf:
                                    - $ref: ../../adaProperties/files/schema.yaml
                                    - type: object
                                      properties:
                                       "schema:contentURL": false
                                       "@type":
                                          description: add MediaObject as type for ROCrate compatibility; this file is part of an archive, not independently accessible
                                          contains:
                                            const: "schema:MediaObject"
                                          not:
                                            contains:
                                              const: "schema:DataDownload"
                required:
                  - "@type"
                  - "schema:serviceType"
                  - "schema:potentialAction"
