$schema: https://json-schema.org/draft/2020-12/schema
$id: https://w3id.org/adaJSONLD/schema/1.0
title: Astromat Archive Product Metadata
description: >-
  Schema for JSON metadata documenting products in Astromata Data Archive (ADA).
  Each project consists of one or more data files and 0 to many supplemental files.
  Each file MUST have an associated YAML metadata file, with the same name,
  but '.yaml' as the file extension.
type: object
properties:
  "@id":
    type: string
  "@type":
    type: array
    items:
      type: string
      enum:
        - "schema:Dataset"
        - "schema:Product"
  "schema:name":
    type: string
  "schema:description":
    type: string
  "schema:additionalType":
    type: array
    description: >-
      Should have the ada product type and 'ada:DataDeliveryPackage'
    items:
      type: string
  submissionType:
    type: string
  "schema:funding":
    type: array
    items:
      type: object
      properties:
        "@type":
          type: string
          default: "schema:MonetaryGrant"
          const: "schema:MonetaryGrant"
        identifier:
          type: string
          description: String that identifies a particular grant
        name:
          type: string
          description: Title of the grant
        funder:
          anyOf:
            - type: object
              properties:
                "@id":
                  type: string
                  description: Identifier for an agent defined in metadata or externally
            - $ref: ../../adaProperties/instrument/schema.yaml
            - type: object
              properties:
                "@type":
                  anyOf:
                    - const:
                        - "schema:Organization"
                    - const:
                        - "schema:FundingAgency"
                  default:
                    - "schema:Organization"
                "schema:name":
                  type: string
              required:
                - "@type"
                - "schema:name"
  "schema:identifier":
    description: Primary identifier for the dataset
    anyOf:
      - type: array
        minItems: 1
        items:
          anyOf:
            - type: object
              properties:
                "@type":
                  type: string
                  const: "schema:PropertyValue"
                  default: "schema:PropertyValue"
                "schema:propertyID":
                  type: string
                  default: "https://registry.identifiers.org/registry/doi"
                "schema:value":
                  type: string
                "schema:url":
                  type: string
            - type: string
      - type: object
        properties:
          "@type":
            type: string
            const: "schema:PropertyValue"
            default: "schema:PropertyValue"
          "schema:propertyID":
            type: string
          "schema:value":
            type: string
          "schema:url":
            type: string
      - type: string
  "schema:creator":
    description: Author or originator of intellectual content of dataset
    type: array
    items:
      type: object
      properties:
        "@list":
          type: array
          items:
            anyOf:
              - type: object
                properties:
                  "@id":
                    type: string
                  "@type":
                    type: string
                    const: "schema:Person"
                    default: "schema:Person"
                  "schema:name":
                    type: string
                  "schema:alternateName":
                    type: string
                  "schema:affiliation":
                    type: object
                  "schema:description":
                    type: string
                  "schema:identifier":
                    anyOf:
                      - type: object
                      - type: string
                  "schema:sameAs":
                    type: array
                    items:
                      type: string
                required:
                  - "@type"
                  - "schema:name"
              - type: object
                properties:
                  "@id":
                    type: string
                  "@type":
                    anyOf:
                      - const:
                          - "schema:Organization"
                      - const:
                          - "schema:ResearchOrganization"
                    default:
                      - "schema:Organization"
                  "schema:name":
                    type: string
                required:
                  - "@type"
                  - "schema:name"
  "schema:contributor":
    description: Other parties who played a role in production of dataset
    type: array
    items:
      anyOf:
        - type: string
        - type: object
          properties:
            "@id":
              type: string
        - type: object
          properties:
            "@type":
              type: string
              const: "schema:Person"
            "schema:name":
              type: string
          required:
            - "@type"
            - "schema:name"
        - type: object
          properties:
            "@type":
              anyOf:
                - const:
                    - "schema:Organization"
          "schema:name":
            type: string
        - type: object
          description: Role-based contributor
          properties:
            "@type":
              type: string
              default: "Role"
              const: "Role"
            roleName:
              type: string
            contributor:
              type: object
  "schema:license":
    description: Legal statement of conditions for use and access
    type: array
    minItems: 0
    items:
      anyOf:
        - type: string
        - $ref: ../../adaProperties/creativeWork/schema.yaml
  "schema:relatedLink":
    type: array
    description: Links to related resources at the product level
    items:
      type: object
      properties:
        "@type":
          type: string
          const: "schema:LinkRole"
        "schema:linkRelationship":
          type: string
        "schema:target":
          type: object
          properties:
            "@type":
              type: string
              const: "schema:EntryPoint"
            "schema:encodingFormat":
              type: string
            "schema:name":
              type: string
            "schema:url":
              type: string
  "schema:dateModified":
    type: string
  "schema:datePublished":
    type: string
  "schema:creativeWorkStatus":
    type: string
  "schema:measurementTechnique":
    type: object
    description: Text description of the measurement method
    properties:
      "@type":
        const: "schema:DefinedTerm"
      "schema:name":
        type: string
      "schema:identifier":
        type: string
  "prov:wasGeneratedBy":
    type: object
    properties:
      "@type":
        description: >-
          Include 'schema:Event', 'xas:AnalysisEvent', 'prov:Activity'
        type: array
        items:
          type: string
      "prov:used":
        type: array
        description: Instruments used in the analysis
        items:
          $ref: ../../adaProperties/instrument/schema.yaml
      "schema:location":
        $ref: ../../adaProperties/laboratory/schema.yaml
      "schema:mainEntity":
        type: array
        description: Samples analyzed
        items:
          type: object
          properties:
            "@type":
              const:
                - "schema:Thing"
                - "https://w3id.org/isample/vocabulary/materialsampleobjecttype/materialsample"
            "schema:additionalType":
              type: array
              items:
                type: string
            "schema:identifier":
              type: string
      "schema:identifier":
        description: Identifier for the analysis event (sessionID)
        type: string
      "schema:startDate":
        type: string
    required:
      - "prov:used"
  "schema:variableMeasured":
    description: >-
      What does the dataset measure? Define the variables here at the conceptual
      level; the physical implementation details are in the data structure.
    type: array
    items:
      type: object
      properties:
        "@id":
          type: string
        "@type":
          const: "schema:PropertyValue"
        "schema:description":
          type: string
        "schema:name":
          type: string
        "schema:alternateName":
          type: array
          items:
            type: string
        "schema:propertyID":
          type: array
          items:
            type: string
        "schema:maxValue":
          type: number
        "schema:minValue":
          type: number
        "cdi:unitOfMeasureKind":
          type: string
      required:
        - "@id"
        - "schema:description"
        - "schema:name"
  "schema:distribution":
    type: array
    description: Access options for the dataset
    items:
      type: object
      properties:
        "@type":
          type: array
          items:
            type: string
            const: "schema:DataDownload"
        "schema:encodingFormat":
          type: string
          default: "application/zip"
        "schema:description":
          type: string
        "schema:contentURL":
          type: string
          format: anyURI
        "schema:hasPart":
          type: array
          description: Files in the zip archive
          items:
            $ref: ../../adaProperties/files/schema.yaml
  "schema:subjectOf":
    type: object
    description: Metadata record about this dataset
    properties:
      "@type":
        type: string
        const: "schema:Dataset"
      "@id":
        type: string
        description: Identifier for the metadata record
      "schema:about":
        type: object
        properties:
          "@id":
            type: string
      "dcterms:conformsTo":
        type: array
        items:
          type: object
          properties:
            "$id":
              type: string
      "schema:maintainer":
        anyOf:
          - type: object
            properties:
              "@type":
                type: string
                const: "schema:Person"
              "schema:name":
                type: string
            required:
              - "@type"
              - "schema:name"
          - type: object
            properties:
              "@type":
                anyOf:
                  - const:
                      - "schema:Organization"
              "schema:name":
                type: string
            required:
              - "schema:name"
      "schema:sdDatePublished":
        description: Date of most recent update to the metadata content
        type: string
        format: datetime
      "schema:includedInDataCatalog":
        type: object
        properties:
          "@id":
            type: string
          "@type":
            type: string
            default: "schema:DataCatalog"
            const: "schema:DataCatalog"
          "schema:name":
            type: string
          "schema:url":
            type: string
          "schema:identifier":
            type: object
            properties:
              "@type":
                type: string
                const: "schema:PropertyValue"
              "schema:propertyID":
                type: string
              "schema:value":
                type: string
              "schema:url":
                type: string
