$schema: https://json-schema.org/draft/2020-12/schema
title: Creative Work Type
description: >-
  Shell type for labeled links to other resources. Any schema.org CreativeWork
  property could be included.
type: object
properties:
  "@type":
    type: string
    default: "schema:CreativeWork"
    const: "schema:CreativeWork"
  "schema:name":
    type: string
  "schema:description":
    type: string
  "schema:url":
    type: string
required:
  - "@type"
