$schema: https://json-schema.org/draft/2020-12/schema
title: SLS Instrument Detail
description: Structured Light Scanning shape models and partial scans
type: object
properties:
  "@type":
    anyOf:
      - const: "ada:SLSShapeModel"
      - const: "ada:SLSPartialScan"
  countScans:
    type: integer
  facets:
    type: integer
  unitsOfMeasurement:
    type: string
  version:
    type: integer
  vertices:
    type: integer
  watertight:
    type: boolean
