$schema: https://json-schema.org/draft/2020-12/schema
title: ADA AMS Product Profile
description: >-
  Technique-specific profile for Accelerator Mass Spectrometry (AMS) products.
  Extends the base ADA product profile with constraints on valid AMS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a AMS product type identifier.
        contains:
          enum:
            - "Accelerator Mass Spectrometry (AMS)"
            - "Accelerator Mass Spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:AMSRawData"
                          - "ada:AMSProcessedData"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:other"
                          - "ada:calibrationFile"
