$schema: https://json-schema.org/draft/2020-12/schema
title: ADA SEM Product Profile
description: >-
  Technique-specific profile for Scanning Electron Microscopy (SEM) products.
  Extends the base ADA product profile with constraints on valid SEM component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a SEM product type identifier.
        contains:
          enum:
            - "ada:SEMImageCollection"
            - "ada:SEMImageMap"
            - "ada:SEMEBSDGrainImage"
            - "ada:SEMEBSDGrainImageMap"
            - "ada:SEMEBSDGrainImageMapCube"
            - "ada:SEMEDSElementalMap"
            - "ada:SEMEDSElementalMaps"
            - "ada:SEMEDSElementalMapsCube"
            - "ada:SEMEDSPointData"
            - "ada:SEMEDSPointDataCollection"
            - "ada:SEMEDSPointDataCube"
            - "ada:SEMHRCLImage"
            - "ada:SEMHRCLMap"
            - "ada:SEMHRCLCube"
            - "Scanning electron microscopy"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:SEMImageCollection"
                          - "ada:SEMImageMap"
                          - "ada:SEMEBSDGrainImage"
                          - "ada:SEMEBSDGrainImageMap"
                          - "ada:SEMEBSDGrainImageMapCube"
                          - "ada:SEMEDSElementalMap"
                          - "ada:SEMEDSElementalMaps"
                          - "ada:SEMEDSElementalMapsCube"
                          - "ada:SEMEDSPointData"
                          - "ada:SEMEDSPointDataCollection"
                          - "ada:SEMEDSPointDataCube"
                          - "ada:SEMHRCLImage"
                          - "ada:SEMHRCLMap"
                          - "ada:SEMHRCLCube"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:calibrationFile"
