$schema: https://json-schema.org/draft/2020-12/schema
title: ADA LC-MS Product Profile
description: >-
  Technique-specific profile for Liquid Chromatography Mass Spectrometry (LC-MS) products.
  Extends the base ADA product profile with constraints on valid LC-MS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a LC-MS product type identifier.
        contains:
          enum:
            - "ada:LCMSCollection"
            - "ada:LCMSMSCollection"
            - "Liquid chromatography-mass spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:LCMSCollection"
                        - "ada:LCMSMSCollection"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
                  fileDetail:
                    anyOf:
                      - $ref: ../../adaProperties/collection/schema.yaml
                      - $ref: ../../adaProperties/dataCube/schema.yaml
                      - $ref: ../../adaProperties/supDocImage/schema.yaml
                      - $ref: ../../adaProperties/document/schema.yaml
