$schema: https://json-schema.org/draft/2020-12/schema
title: ADA LC-MS Product Profile
description: >-
  Technique-specific profile for Liquid Chromatography Mass Spectrometry (LC-MS) products.
  Extends the base ADA product profile with constraints on valid LC-MS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a LC-MS product type identifier.
        contains:
          enum:
            - "Liquid Chromatography - Mass Spectrometry (LCMS) Collection"
            - "Liquid chromatography-mass spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:LCMSCollection"
                          - "ada:LCMSMSCollection"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
