$schema: https://json-schema.org/draft/2020-12/schema
title: ADA EMPA Product Profile
description: >-
  Technique-specific profile for Electron Microprobe Analysis (EMPA) products.
  Extends the base ADA product profile with constraints on valid EMPA component
  types and empa_detail requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include an EMPA product type identifier.
        contains:
          enum:
            - "Electron Microprobe Analysis (EMPA) Collection"
            - "Electron Microprobe Analysis Image (EMPA)"
            - "Electron Microprobe Analysis Quantitative Elemental Abundances (EMPAQEA)"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:EMPAImageMap"
                          - "ada:EMPAImage"
                          - "ada:EMPAQEATabular"
                          - "ada:EMPAImageCollection"
                          - "ada:EMPAESPCTabular"
                          - "ada:EMPAESPCPlot"
                          - "ada:analysisLocation"
                          - "ada:supplementaryImage"
                          - "ada:calibrationFile"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
