$schema: https://json-schema.org/draft/2020-12/schema
title: ADA LAF Product Profile
description: >-
  Technique-specific profile for Laser-Assisted Fluorination (LAF) products.
  Extends the base ADA product profile with constraints on valid LAF component
  types and detailLAF requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a LAF product type identifier.
        contains:
          enum:
            - "Laser Assisted Fluorination (LAF) Processed"
            - "Laser Assisted Fluorination (LAF) Raw"
            - "Laser Assisted Fluorination"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:LAFProcessed"
                          - "ada:LAFRaw"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:other"
                          - "ada:calibrationFile"
