$schema: https://json-schema.org/draft/2020-12/schema
title: ADA RI-TOF-NGMS Product Profile
description: >-
  Technique-specific profile for Resonance Ionization Time-of-Flight Noble Gas Mass Spectrometry (RI-TOF-NGMS) products.
  Extends the base ADA product profile with constraints on valid RI-TOF-NGMS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a RI-TOF-NGMS product type identifier.
        contains:
          enum:
            - "ada:RITOFNGMSTabular"
            - "ada:RITOFNGMSCollection"
            - "Resonance ionization time of flight noble gas mass spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:RITOFNGMSTabular"
                        - "ada:RITOFNGMSCollection"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
                  fileDetail:
                    anyOf:
                      - $ref: ../../adaProperties/tabularData/schema.yaml
                      - $ref: ../../adaProperties/collection/schema.yaml
                      - $ref: ../../adaProperties/supDocImage/schema.yaml
                      - $ref: ../../adaProperties/document/schema.yaml
