$schema: https://json-schema.org/draft/2020-12/schema
title: ADA GPYC Product Profile
description: >-
  Technique-specific profile for Gas Pycnometry (GPYC) products.
  Extends the base ADA product profile with constraints on valid GPYC component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a GPYC product type identifier.
        contains:
          enum:
            - "ada:GPYCProcessedTabular"
            - "ada:GPYCRawTabular"
            - "Gas pycnometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:GPYCProcessedTabular"
                        - "ada:GPYCRawTabular"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
