$schema: https://json-schema.org/draft/2020-12/schema
title: ADA GPYC Product Profile
description: >-
  Technique-specific profile for Gas Pycnometry (GPYC) products.
  Extends the base ADA product profile with constraints on valid GPYC component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a GPYC product type identifier.
        contains:
          enum:
            - "Gas Pycnometry (GPYC) Processed"
            - "Gas Pycnometry (GPYC) Raw"
            - "Gas pycnometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:GPYCProcessedTabular"
                          - "ada:GPYCRawTabular"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
