$schema: https://json-schema.org/draft/2020-12/schema
title: Supplemental Document Image Type
description: >-
  Supplemental document images including analysis location images, annotated products,
  context photography, and other supplemental visual materials.
type: object
properties:
  "@type":
    type: array
    items:
      type: string
    minItems: 2
    allOf:
      - contains:
          const: "ada:image"
      - contains:
          const: "schema:DigitalDocument"
    description: GeneralType for supplemental document images
  componentType:
    type: object
    properties:
      "@type":
        enum:
          - "ada:analysisLocation"
          - "ada:annotatedProduct"
          - "ada:contextPhotography"
          - "ada:areaOfInterest"
          - "ada:instrumentMetadata"
          - "ada:supplementalBasemap"
          - "ada:other"
          - "ada:plot"
          - "ada:quickLook"
          - "ada:report"
          - "ada:visImage"
    required:
      - "@type"
  numPixelsX:
    type: integer
  numPixelsY:
    type: integer
  _original_name:
    type: string
required:
  - "@type"
  - componentType
