$schema: https://json-schema.org/draft/2020-12/schema
title: Document Type
description: >-
  Text or PDF/A documents providing supplemental information, typically related
  to calibration, instrument metadata details, analysis methods, or data
  representation. Typed as ada:document and schema:DigitalDocument.
type: object
properties:
  "@type":
    const:
      - "ada:document"
      - "schema:DigitalDocument"
  componentType:
    description: One of the supplemental document types if applicable
    anyOf:
      - type: object
        properties:
          "@type":
            enum:
              - "ada:calibrationFile"
              - "ada:contextVideo"
              - "ada:logFile"
              - "ada:methodDescription"
              - "ada:peaks"
              - "ada:processingDescription"
              - "ada:QRISCalibrationFile"
              - "ada:samplePreparation"
              - "ada:shapefiles"
      - $ref: ../details/schema.yaml#/$defs/argt_detail
  "schema:version":
    type: string
  "schema:isBasedOn":
    description: same as ada/samis '_originalName'
    type: string
required:
  - "@type"
  - componentType
