---
$schema: https://json-schema.org/draft/2020-12/schema
title: PROV-O Provenance Activity
description: PROV-O native provenance activity building block for CDIF. Extends the
  minimal prov:Activity (generatedBy) with W3C PROV-O properties for comprehensive
  provenance documentation. Uses schema.org fallbacks only where PROV-O has no equivalent
  (name, description, instrument, methodology, status).
type: object
allOf:
- $ref: ../generatedBy/schema.yaml
- type: object
  properties:
    '@type':
      type: array
      items:
        type: string
      minItems: 1
      contains:
        const: prov:Activity
      description: Must include prov:Activity. Unlike cdifProv, does not require
        schema:Action dual typing.
    'schema:name':
      type: string
      description: Human-readable name for the activity (schema.org fallback -- PROV-O
        has no name property)
    'schema:description':
      type: string
      description: Text description of what this activity did (schema.org fallback
        -- PROV-O has no description property)
    'prov:generated':
      description: Entities produced by this activity (inverse of prov:wasGeneratedBy)
      type: array
      items:
        anyOf:
        - type: string
        - type: object
          properties:
            '@id':
              type: string
              description: reference to an entity produced by this activity
    'prov:wasAssociatedWith':
      description: Agents responsible for this activity (PROV-O native -- maps to
        schema:agent in cdifProv)
      type: array
      items:
        anyOf:
        - $ref: '#/$defs/Person'
        - $ref: '#/$defs/Organization'
        - $ref: '#/$defs/AgentInRole'
        - type: string
        - type: object
          properties:
            '@id':
              type: string
              description: reference to an agent defined elsewhere
    'prov:wasInformedBy':
      description: Other activities that communicated information to this one (PROV-O
        activity-to-activity chain -- maps to schema:object in cdifProv)
      type: array
      items:
        anyOf:
        - type: object
          properties:
            '@id':
              type: string
              description: reference to a prior activity
        - type: string
    'prov:startedAtTime':
      type: string
      description: ISO8601 date-time when the activity started (PROV-O native -- maps
        to schema:startTime in cdifProv)
    'prov:endedAtTime':
      type: string
      description: ISO8601 date-time when the activity ended (PROV-O native -- maps
        to schema:endTime in cdifProv)
    'prov:atLocation':
      description: Location where the activity occurred (PROV-O expanded term -- maps
        to schema:location in cdifProv)
      anyOf:
      - $ref: '#/$defs/SpatialExtent'
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a place defined elsewhere
    'prov:wasStartedBy':
      description: Entity that triggered the start of this activity (PROV-O expanded
        term)
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a triggering entity
    'prov:wasEndedBy':
      description: Entity that triggered the end of this activity (PROV-O expanded
        term)
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to an entity that ended this activity
    'schema:actionStatus':
      type: string
      description: Status of this activity (schema.org fallback -- no PROV-O equivalent)
      enum:
      - schema:CompletedActionStatus
      - schema:ActiveActionStatus
      - schema:PotentialActionStatus
      - schema:FailedActionStatus
    'schema:actionProcess':
      description: Methodology or protocol for this activity (schema.org fallback
        -- PROV-O has prov:hadPlan only inside qualified Association)
      anyOf:
      - $ref: '#/$defs/HowTo'
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a methodology defined elsewhere
    'schema:error':
      type: string
      description: Error description for failed activities (schema.org fallback --
        no PROV-O equivalent)
$defs:
  Person:
    $ref: ../../schemaorgProperties/person/schema.yaml
  Organization:
    $ref: ../../schemaorgProperties/organization/schema.yaml
  AgentInRole:
    $ref: ../../schemaorgProperties/agentInRole/schema.yaml
  Instrument:
    $ref: ../../schemaorgProperties/instrument/schema.yaml
  DefinedTerm:
    $ref: ../../schemaorgProperties/definedTerm/schema.yaml
  LabeledLink:
    $ref: ../../schemaorgProperties/labeledLink/schema.yaml
  SpatialExtent:
    $ref: ../../schemaorgProperties/spatialExtent/schema.yaml
  HowTo:
    type: object
    description: A methodology or protocol described as a HowTo with optional steps
    properties:
      '@type':
        type: string
        const: schema:HowTo
      '@id':
        type: string
      'schema:name':
        type: string
        description: Name of the methodology or protocol
      'schema:description':
        type: string
        description: Description of the methodology
      'schema:url':
        type: string
        format: uri
        description: URL to a published methodology or protocol document
      'schema:step':
        type: array
        description: Ordered steps in this methodology
        items:
          $ref: '#/$defs/HowToStep'
    required:
    - '@type'
    anyOf:
    - required:
      - schema:name
    - required:
      - schema:url
  HowToStep:
    type: object
    description: A single step in a HowTo methodology
    properties:
      '@type':
        type: string
        const: schema:HowToStep
      'schema:name':
        type: string
        description: Name of this step
      'schema:description':
        type: string
        description: Description of what this step involves
      'schema:url':
        type: string
        format: uri
        description: URL to documentation for this step
      'schema:position':
        type: integer
        description: Ordinal position of this step
    required:
    - '@type'
    - schema:name
