$schema: https://json-schema.org/draft/2020-12/schema
title: ADA UVFM Product Profile
description: >-
  Technique-specific profile for Ultraviolet Fluorescence Microscopy (UVFM) products.
  Extends the base ADA product profile with constraints on valid UVFM component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a UVFM product type identifier.
        contains:
          enum:
            - "Fluorescence Microscopy (UVFM) Image"
            - "UV Fluorescence Microscopy"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:UVFMImage"
                          - "ada:UVFMImageCollection"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:other"
                          - "ada:calibrationFile"
