$schema: https://json-schema.org/draft/2020-12/schema
title: Spatial Registration Type
description: >-
  Defines pixel coordinate system registration including origin coordinates,
  pixel scales, and coordinate definition type for spatially registered images
  and maps.
type: object
properties:
  basemap:
    type: string
    description: link to appropriate basemap image map
  originX:
    type: number
  originY:
    type: number
  originZ:
    type: number
  coordDef:
    type: string
    description: >-
      Whether coordinates are stage-defined or pixel-defined. If pixel-defined,
      are coordinates from stage, upperleftPixel, or centerPixel.
  coordUnits:
    type: string
  pixelUnits:
    type: string
  pixelScaleX:
    type: number
  pixelScaleY:
    type: number
  originLocation:
    type: string
    description: >-
      The location of the origin pixel of an image.
      Range: upperLeft, upperRight, lowerLeft, lowerRight, center
required:
  - originX
  - originY
  - pixelScaleX
  - pixelScaleY
  - pixelUnits
  - originLocation
  - coordDef
