$schema: https://json-schema.org/draft/2020-12/schema
title: Instrument Detail Types
description: >-
  Umbrella schema referencing all instrument-specific detail type building blocks.
  Individual detail types are now separate building blocks under adaProperties/detailXxx/.
type: object
anyOf:
  - $ref: ../detailBasemap/schema.yaml
  - $ref: ../detailARGT/schema.yaml
  - $ref: ../detailDSC/schema.yaml
  - $ref: ../detailEMPA/schema.yaml
  - $ref: ../detailEAIRMS/schema.yaml
  - $ref: ../detailICPOES/schema.yaml
  - $ref: ../detailL2MS/schema.yaml
  - $ref: ../detailLAF/schema.yaml
  - $ref: ../detailNanoIR/schema.yaml
  - $ref: ../detailNanoSIMS/schema.yaml
  - $ref: ../detailPSFD/schema.yaml
  - $ref: ../detailVNMIR/schema.yaml
  - $ref: ../detailQRIS/schema.yaml
  - $ref: ../detailSLS/schema.yaml
  - $ref: ../detailXCT/schema.yaml
  - $ref: ../detailXRD/schema.yaml
