$schema: https://json-schema.org/draft/2020-12/schema
title: ADA EA-IRMS Product Profile
description: >-
  Technique-specific profile for Elemental Analysis - Isotope Ratio Mass Spectrometry (EA-IRMS) products.
  Extends the base ADA product profile with constraints on valid EA-IRMS component
  types and detailEAIRMS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a EA-IRMS product type identifier.
        contains:
          enum:
            - "ada:EAIRMSCollection"
            - "Elemental analysis - isotope ratio mass spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:EAIRMSCollection"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:calibrationFile"
