$schema: https://json-schema.org/draft/2020-12/schema
title: ADA XCT Product Profile
description: >-
  Technique-specific profile for X-ray Computed Tomography (XCT) products.
  Extends the base ADA product profile with constraints on valid XCT component
  types and detailXCT requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a XCT product type identifier.
        contains:
          enum:
            - "ada:XCTImageCollection"
            - "X-ray computed tomography"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:XCTImageCollection"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
