---
$schema: https://json-schema.org/draft/2020-12/schema
title: CDIF Provenance Activity
description: Extended provenance activity building block for CDIF. Extends the minimal
  prov:Activity (generatedBy) with schema.org Action properties for comprehensive
  provenance documentation including agents, instruments, methodology, temporal bounds,
  action chaining, and more.
type: object
allOf:
- $ref: ../../provProperties/generatedBy/schema.yaml
- type: object
  properties:
    '@type':
      type: array
      items:
        type: string
      minItems: 2
      contains:
        const: schema:Action
      description: Must include both schema:Action and prov:Activity (prov:Activity
        required by base generatedBy schema)
    'schema:name':
      type: string
      description: Human-readable name for the activity
    'schema:description':
      type: string
      description: Text description of what this activity did
    'schema:identifier':
      description: Formal identifier for this activity
      anyOf:
      - $ref: '#/$defs/Identifier'
      - type: string
    'schema:agent':
      description: Primary responsible agent for this activity (maps to PROV wasAssociatedWith)
      anyOf:
      - $ref: '#/$defs/Person'
      - $ref: '#/$defs/Organization'
      - $ref: '#/$defs/AgentInRole'
      - type: object
        properties:
          '@id':
            type: string
            description: reference to an agent defined elsewhere
    'schema:participant':
      description: Other participants in this activity
      type: array
      items:
        anyOf:
        - $ref: '#/$defs/Person'
        - $ref: '#/$defs/Organization'
        - $ref: '#/$defs/AgentInRole'
        - type: object
          properties:
            '@id':
              type: string
              description: reference to a participant defined elsewhere
    'schema:object':
      description: Input entity for this activity (for action chaining, references the
        result of a prior activity)
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to an input entity
    'schema:result':
      description: Output entity produced by this activity (for action chaining, can
        be referenced as object of a subsequent activity)
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to an output entity
    'schema:actionStatus':
      type: string
      description: Status of this activity
      enum:
      - schema:CompletedActionStatus
      - schema:ActiveActionStatus
      - schema:PotentialActionStatus
      - schema:FailedActionStatus
    'schema:startTime':
      type: string
      description: ISO8601 date-time when the activity started (maps to PROV startedAtTime)
    'schema:endTime':
      type: string
      description: ISO8601 date-time when the activity ended (maps to PROV endedAtTime)
    'schema:location':
      description: Where the activity occurred
      anyOf:
      - $ref: '#/$defs/SpatialExtent'
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a place defined elsewhere
    'schema:actionProcess':
      description: Methodology or protocol for this activity
      anyOf:
      - $ref: '#/$defs/HowTo'
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a methodology defined elsewhere
    'schema:error':
      type: string
      description: Error description for failed activities
    'schema:additionalProperty':
      description: Domain-specific extension properties
      type: array
      items:
        $ref: '#/$defs/AdditionalProperty'
$defs:
  Person:
    $ref: ../../schemaorgProperties/person/schema.yaml
  Organization:
    $ref: ../../schemaorgProperties/organization/schema.yaml
  AgentInRole:
    $ref: ../../schemaorgProperties/agentInRole/schema.yaml
  Identifier:
    $ref: ../../schemaorgProperties/identifier/schema.yaml
  Instrument:
    $ref: ../../schemaorgProperties/instrument/schema.yaml
  DefinedTerm:
    $ref: ../../schemaorgProperties/definedTerm/schema.yaml
  LabeledLink:
    $ref: ../../schemaorgProperties/labeledLink/schema.yaml
  SpatialExtent:
    $ref: ../../schemaorgProperties/spatialExtent/schema.yaml
  AdditionalProperty:
    $ref: ../../schemaorgProperties/additionalProperty/schema.yaml
  HowTo:
    type: object
    description: A methodology or protocol described as a HowTo with optional steps
    properties:
      '@type':
        type: string
        const: schema:HowTo
      '@id':
        type: string
      'schema:name':
        type: string
        description: Name of the methodology or protocol
      'schema:description':
        type: string
        description: Description of the methodology
      'schema:url':
        type: string
        format: uri
        description: URL to a published methodology or protocol document
      'schema:step':
        type: array
        description: Ordered steps in this methodology
        items:
          $ref: '#/$defs/HowToStep'
    required:
    - '@type'
    anyOf:
    - required:
      - schema:name
    - required:
      - schema:url
  HowToStep:
    type: object
    description: A single step in a HowTo methodology
    properties:
      '@type':
        type: string
        const: schema:HowToStep
      'schema:name':
        type: string
        description: Name of this step
      'schema:description':
        type: string
        description: Description of what this step involves
      'schema:url':
        type: string
        format: uri
        description: URL to documentation for this step
      'schema:position':
        type: integer
        description: Ordinal position of this step
    required:
    - '@type'
    - schema:name
  Claim:
    type: object
    description: A statement or assertion about the dataset, such as a quality claim
    properties:
      '@type':
        type: string
        const: schema:Claim
      '@id':
        type: string
      'schema:claimReviewed':
        type: string
        description: The claim being reviewed or asserted
      'schema:author':
        description: Author of this claim
        anyOf:
        - $ref: '#/$defs/Person'
        - $ref: '#/$defs/Organization'
        - type: object
          properties:
            '@id':
              type: string
      'schema:datePublished':
        type: string
        description: ISO8601 date when this claim was published
      'schema:appearance':
        description: Where this claim appears
        anyOf:
        - type: string
        - $ref: '#/$defs/LabeledLink'
    required:
    - '@type'
    - schema:claimReviewed
