$schema: https://json-schema.org/draft/2020-12/schema
description: schema to document file-based access to a resoruce via URL, based on schema.org/DataDownload
type: object
properties:
  '@id': 
    type: string
  '@type':
    type: array
    description: implement as array because extensions might need to add additional types
    items:
      type: string
    contains:
      const: schema:DataDownload
    minItems: 1
  'schema:name':
    type: string
  'schema:contentUrl':
    type: string
    format: uri
  'schema:encodingFormat':
    type: array
    items:
      type: string
  'spdx:checksum':
    type: object
    description: A string value calculated from the content of the resource representation, used to test
      if content has been modified. The checksum is a property of a particular distribution/DataDownload.
    properties:
      'spdx:algorithm':
        type: string
      'spdx:checksumValue':
        type: string
  'schema:provider':
    type: array
    description: Party who maintains this particular distribution option for the dataset. Use this property
      if there are multiple distributions from different providers
    items:
      anyOf:
      - type: object
        properties: 
          '@id': 
            type: string
      - $ref: ../person/schema.yaml
      - $ref: ../organization/schema.yaml
required:
- 'schema:contentUrl'
- '@type'