---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
allOf:
- $ref: ../../cdifProperties/cdifCatalogRecord/schema.yaml
- properties:
    'dcterms:conformsTo':
      type: array
      items:
        $ref: ../../cdifProperties/cdifCatalogRecord/schema.yaml#/$defs/conformsTo_item
      minItems: 2
      contains:
        type: object
        properties:
          '@id':
            const: 'cdif:profile_xasCDIF'
        required:
        - '@id'
      minContains: 1