$schema: https://json-schema.org/draft/2020-12/schema
title: ADA VNMIR Product Profile
description: >-
  Technique-specific profile for Very-Near Mid-Infrared (VNMIR/FTIR) spectroscopy
  products. Extends the base ADA product profile with constraints on valid VNMIR
  component types and vnmir_detail requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a VNMIR product type identifier.
        contains:
          enum:
            - "Visible, near-infrared, and mid-infrared Spectroscopy (VNMIR) Point"
            - "Visible, near-infrared, and mid-infrared Spectroscopy (VNMIR) Overview Image"
            - "Visible, near-infrared, and mid-infrared Spectroscopy (VNMIR) Spectral Map"
            - "Visible, near-, and mid-infrared spectroscopy"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:VNMIRSpectralPoint"
                          - "ada:VNMIROverviewImage"
                          - "ada:VNMIRSpectralMap"
                          - "ada:VNMIRSpectraPlot"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
