$schema: https://json-schema.org/draft/2020-12/schema
title: ADA VLM Product Profile
description: >-
  Technique-specific profile for Visible Light Microscopy (VLM) products.
  Extends the base ADA product profile with constraints on valid VLM component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a VLM product type identifier.
        contains:
          enum:
            - "ada:VLMImage"
            - "ada:VLMImageCollection"
            - "Visible Light Microscopy"
            - "Visible Light Microscopy Basemap"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:VLMImage"
                        - "ada:VLMImageCollection"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
