$schema: https://json-schema.org/draft/2020-12/schema
title: ADA XRD Product Profile
description: >-
  Technique-specific profile for X-ray Diffraction (XRD) products.
  Extends the base ADA product profile with constraints on valid XRD component
  types and xrd_detail requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include an XRD product type identifier.
        contains:
          enum:
            - "X-ray Diffraction (XRD) Tabular"
            - "X-ray diffraction"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:XRDTabular"
                          - "ada:XRDDiffractionPattern"
                          - "ada:XRDIndexedImage"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:calibrationFile"
                          - "ada:other"
