$schema: https://json-schema.org/draft/2020-12/schema
title: ADA NanoIR Product Profile
description: >-
  Technique-specific profile for Nano-Infrared Spectroscopy (NanoIR) products.
  Extends the base ADA product profile with constraints on valid NanoIR component
  types and detailNanoIR requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a NanoIR product type identifier.
        contains:
          enum:
            - "ada:NanoIRBackground"
            - "ada:NanoIRMap"
            - "ada:NanoIRMapCollection"
            - "ada:NanoIRPointCollection"
            - "Nanoscale Infrared Mapping"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:NanoIRBackground"
                        - "ada:NanoIRMap"
                        - "ada:NanoIRMapCollection"
                        - "ada:NanoIRPointCollection"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
