$schema: https://json-schema.org/draft/2020-12/schema
title: ADA NanoIR Product Profile
description: >-
  Technique-specific profile for Nano-Infrared Spectroscopy (NanoIR) products.
  Extends the base ADA product profile with constraints on valid NanoIR component
  types and detailNanoIR requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a NanoIR product type identifier.
        contains:
          enum:
            - "Nanoscale Infrared Mapping (NanoIR) Background"
            - "Nanoscale Infrared Mapping (NanoIR) MapCollection"
            - "Nanoscale Infrared Mapping (NanoIR) Point Data"
            - "Nanoscale Infrared Mapping"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:NanoIRBackground"
                          - "ada:NanoIRMap"
                          - "ada:NanoIRMapCollection"
                          - "ada:NanoIRPointCollection"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:other"
                          - "ada:calibrationFile"
