$schema: https://json-schema.org/draft/2020-12/schema
title: ADA SV-RUEC Product Profile
description: >-
  Technique-specific profile for Seismic Velocities and Rock Ultrasonic Elastic Constants (SV-RUEC) products.
  Extends the base ADA product profile with constraints on valid SV-RUEC component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a SV-RUEC product type identifier.
        contains:
          enum:
            - "Seismic Velocities and Rock Ultrasonic Elastic Constants (SVRUEC)"
            - "Seismic Velocities and Rock Ultrasonic Elastic Constants"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:SVRUECTabular"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:other"
                          - "ada:calibrationFile"
