---
$schema: https://json-schema.org/draft/2020-12/schema
description: CDIF schema.org implemenation of PropertyValue to use as values for variableMeasured
type: object
properties:
  '@type':
    type: array
    items:
      type: string
    contains:
      const: schema:PropertyValue
    minItems: 1
  '@id':
    type: string
  'schema:name':
    type: string
    description: this is the string label that is expected to be associated with the variable in the dataset
      serialization
  'schema:description':
    type: string
    default: missing
  'schema:alternateName':
    type: array
    items:
      type: string
      description: human intelligible name for variable that conveys semantics
  'schema:propertyID':
    type: array
    items:
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a skos concept for the property
      - $ref: '#/$defs/DefinedTerm'
    description: identifier or name for the property concept quantified by the values in this variable
      slot. Multiple values can specify the property at different levels of granularity.
  'schema:measurementTechnique':
    anyOf:
    - type: string
    - type: object
      properties:
        '@id':
          type: string
          description: reference to a skos concept for the property
    - $ref: '#/$defs/DefinedTerm'
    description: A text description of the measurement method used to determine values for this variable.
      If standard measurement protocols are defined and registered, these can be identified via http URI's.
  'schema:unitText':
    type: string
    description: A string that identifies a unit of measurement that applies to all values for this variable.
  'schema:unitCode':
    anyOf:
    - type: string
    - type: object
      properties:
        '@id':
          type: string
          description: reference to a skos concept for the property
    - $ref: '#/$defs/DefinedTerm'
    description: Value is expected to be TEXT or URL. We recommend providing an HTTP URI that identifies
      a unit of measure from a vocabulary accessible on the web. The QUDT unit vocabulary provides and
      extensive set of registered units of measure that can be used to populate the schema:unitCode property
      to specify the units of measure used to report datavalues when that is appropriate.
  'schema:minValue':
    type: number
    description: ' If the value for the variable is numeric, this is the minimum value that occurs in
      the dataset. Not useful for other value types.'
  'schema:maxValue':
    type: number
    description: ' If the value for the variable is numeric, this is the maximum value that occurs in
      the dataset. Not useful for other value types.'
  'schema:url':
    type: string
    format: uri
    description: Any schema:Thing can have a URL property, but because the value is simply a url the relationship
      of the linked resource can not be expressed. Usage is optional. The recommendation is that schema:url
      should link to a web page that would be useful for a person to interpret the variable, but is not
      intended to be machine-actionable.
$defs:
  DefinedTerm:
    $ref: ../definedTerm/schema.yaml
allOf:
- required:
  - '@type'
  - schema:name
  - schema:description