$schema: https://json-schema.org/draft/2020-12/schema
title: XRD Instrument Detail
description: X-ray Diffraction tabular data with geometry and wavelength
type: object
properties:
  "@type":
    const: "ada:XRDTabular"
  geometry:
    type: string
  sampleMount:
    type: string
  stepSize:
    type: number
  timePerStep:
    type: number
  wavelength:
    type: number
