---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: additionalProperty PropertyValue
description: 'PropertyValue values required to define a soft-typed property with a value. '
properties:
  '@type':
    type: string
    const: schema:PropertyValue
  'schema:propertyID':
    type: array
    items:
      $ref: '#/$defs/propertyID_item'
    minItems: 1
    description: identifier or name for the property concept quantified by the values in this variable
      slot. Multiple values can specify the property at different levels of granularity.
  'schema:name':
    type: string
  'schema:value':
    type: string
required:
- 'schema:name'
- 'schema:value'
$defs:
  DefinedTerm:
    $ref: ../definedTerm/schema.yaml
  propertyID_item:
    anyOf:
    - type: string
    - type: object
      properties:
        '@id':
          type: string
    - $ref: '#/$defs/DefinedTerm'