$schema: https://json-schema.org/draft/2020-12/schema
description: For more granularity on how a person contributed to a Dataset, use schema:Role. The schema.org
  documentation does not state that the Role type is an expected data type of author, creator and contributor,
  but that is addressed in this blog post (http://blog.schema.org/2014/06/introducing-role.html). see
  https://github.com/ESIPFed/science-on-schema.org/blob/develop/guides/Dataset.md#roles-of-people
type: object
properties:
  '@type':
    type: string
    default: schema:Role
    const: schema:Role
  'schema:roleName':
    anyOf:
      - type: string
      - $ref: ../definedTerm/schema.yaml
  'schema:contributor':
    oneOf:
      - $ref: ../person/schema.yaml
      - $ref: ../organization/schema.yaml
required:
  - schema:roleName
  - schema:contributor