$schema: https://json-schema.org/draft/2020-12/schema
title: ADA ToF-SIMS Product Profile
description: >-
  Technique-specific profile for Time-of-Flight Secondary Ion Mass Spectrometry (ToF-SIMS) products.
  Extends the base ADA product profile with constraints on valid ToF-SIMS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a ToF-SIMS product type identifier.
        contains:
          enum:
            - "Time-of-flight secondary ion mass spectrometry (TOFSIMS)"
            - "Time-of-Flight Secondary Ion Mass Spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:TOFSIMSCollection"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
