$schema: https://json-schema.org/draft/2020-12/schema
description: Funding acknowledgement properties, profile of schema.org/MonetaryGrant
type: object
properties:
  '@type':
    type: string
    default: schema:MonetaryGrant
    const: schema:MonetaryGrant
  schema:identifier:
    $ref: '#/$defs/Identifier'
    description: identifier for a particular grant
  schema:description:
    type: string
    description: description of the funding or grant
  schema:name:
    type: string
    description: title of the grant
  schema:funder:
    anyOf:
    - type: object
      properties:
        '@id':
          type: string
          description: a identifier for an agent defined in this metadata, or externally; must be dereferenceable
    - $ref: '#/$defs/Person'
    - $ref: '#/$defs/Organization'
allOf:
- required:
  - schema:funder
- anyOf:
  - required:
    - schema:identifier
  - required:
    - schema:name
$defs:
  Person:
    $ref: ../person/schema.yaml
  Organization:
    $ref: ../organization/schema.yaml
  Identifier:
    $ref: ../identifier/schema.yaml