$schema: https://json-schema.org/draft/2020-12/schema
title: Tabular Data Type
description: >-
  Tabular/structured data files typed as cdi:PhysicalDataSet and ada:tabularData.
  Includes DDI-CDI WideDataStructure for column layout description.
type: object
properties:
  "@type":
    const:
      - "cdi:PhysicalDataSet"
      - "ada:tabularData"
  componentType:
    anyOf:
      - type: object
        properties:
          "@type":
            enum:
              - "ada:AMSRawData"
              - "ada:AMSProcessedData"
              - "ada:DSCResultsTabular"
              - "ada:FTICRMSTabular"
              - "ada:GPYCProcessedTabular"
              - "ada:GPYCRawTabular"
              - "ada:HRICPMSProcessed"
              - "ada:HRICPMSRaw"
              - "ada:ICPOESIntermediateTabular"
              - "ada:ICPOESProcessedTabular"
              - "ada:ICPOESRawTabular"
              - "ada:ICTabular"
              - "ada:MCICPMSTabular"
              - "ada:NGNSMSRaw"
              - "ada:NGNSMSProcessed"
              - "ada:QICPMSProcessedTabular"
              - "ada:QICPMSRawTabular"
              - "ada:RAMANRawTabular"
              - "ada:RITOFNGMSTabular"
              - "ada:RITOFNGMSCollection"
              - "ada:SEMEDSPointData"
              - "ada:SIMSTabular"
              - "ada:STEMEDSTabular"
              - "ada:STEMEELSTabular"
              - "ada:SVRUECTabular"
              - "ada:XANESRawTabular"
              - "ada:XANESProcessedTabular"
        required:
          - "@type"
      - $ref: ../details/schema.yaml#/$defs/dsc_detail
      - $ref: ../details/schema.yaml#/$defs/eairms_detail
      - $ref: ../details/schema.yaml#/$defs/empa_detail
      - $ref: ../details/schema.yaml#/$defs/laf_detail
      - $ref: ../details/schema.yaml#/$defs/nanosims_detail
      - $ref: ../details/schema.yaml#/$defs/nanoir_detail
      - $ref: ../details/schema.yaml#/$defs/psfd_detail
      - $ref: ../details/schema.yaml#/$defs/vnmir_detail
      - $ref: ../details/schema.yaml#/$defs/xrd_detail
  "cdi:isStructuredBy":
    $ref: ../physicalMapping/schema.yaml
  countRows:
    type: integer
  countColumns:
    type: integer
  xCoordCol:
    description: Column name for X coordinates
    type: string
  yCoordCol:
    type: string
  zCoordCol:
    type: string
  coordUnits:
    type: string
  spatialRegistration:
    $ref: ../spatialRegistration/schema.yaml
required:
  - "@type"
  - componentType
