$schema: https://json-schema.org/draft/2020-12/schema
title: ADA NG-NS-MS Product Profile
description: >-
  Technique-specific profile for Noble Gas and Nitrogen Static Mass Spectrometry (NG-NS-MS) products.
  Extends the base ADA product profile with constraints on valid NG-NS-MS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a NG-NS-MS product type identifier.
        contains:
          enum:
            - "Noble Gas and Nitrogen Static Mass Spectrometry (NGNSMS) Processed"
            - "Noble Gas and Nitrogen Static Mass Spectrometry (NGNSMS) Raw"
            - "Noble gas and Nitrogen Static Mass Spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:NGNSMSRaw"
                          - "ada:NGNSMSProcessed"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
