$schema: https://json-schema.org/draft/2020-12/schema
title: ADA GC-MS Product Profile
description: >-
  Technique-specific profile for Gas Chromatography Mass Spectrometry (GC-MS) products.
  Extends the base ADA product profile with constraints on valid GC-MS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a GC-MS product type identifier.
        contains:
          enum:
            - "Gas Chromatography-Mass Spectrometry (GCMS)"
            - "Gas Chromatography-Mass Spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:GCMSCollection"
                          - "ada:GCMSCube"
                          - "ada:GCGCMSCollection"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
