$schema: https://json-schema.org/draft/2020-12/schema
title: Collection Type
description: >-
  A collection can be a set of files with identical information model and
  serialization/formatting, or a heterogeneous set of files that together
  constitute a dataset (a composite dataset).
type: object
properties:
  "@type":
    const:
      - "ada:collection"
      - "https://schema.org/Collection"
    description: GeneralType for collections
  componentType:
    type: object
    properties:
      "@type":
        type: string
        enum:
          - "ada:AIVAImageCollection"
          - "ada:ARGTCollection"
          - "ada:EAIRMSCollection"
          - "ada:EMPAImageCollection"
          - "ada:GCMSCollection"
          - "ada:GCGCMSCollection"
          - "ada:LCMSCollection"
          - "ada:LCMSMSCollection"
          - "ada:LIT2DDataCollection"
          - "ada:LITPolarDataCollection"
          - "ada:MCICPMSCollection"
          - "ada:NanoIRMapCollection"
          - "ada:NanoIRPointCollection"
          - "ada:NanoSIMSCollection"
          - "ada:NanoSIMSImageCollection"
          - "ada:QRISCalibratedCollection"
          - "ada:QRISRawCollection"
          - "ada:RITOFNGMSCollection"
          - "ada:SEMEDSElementalMaps"
          - "ada:SEMEDSPointDataCollection"
          - "ada:SEMImageCollection"
          - "ada:SIMSCollection"
          - "ada:TEMEDSImageCollection"
          - "ada:TOFSIMSCollection"
          - "ada:UVFMImageCollection"
          - "ada:VLMImageCollection"
          - "ada:XANESCollection"
          - "XCTImageCollection"
  memberTypes:
    description: List of the component types in the collection
    $ref: ../stringArray/schema.yaml
  nFiles:
    type: integer
    description: Number of files in the collection, including metadata files
  filelist:
    type: array
    items:
      type: object
      properties:
        fileName:
          type: string
          description: Full path to file in container object
        fileNamePattern:
          type: string
          description: >-
            Pattern for collection members with differentiating suffix at '*'
        componentType:
          description: The component type for the file(s)
          type: string
        "schema:encodingFormat":
          type: string
          description: MIME type with extension
      oneOf:
        - required:
            - fileName
        - required:
            - fileNamePattern
