---
$schema: https://json-schema.org/draft/2020-12/schema
title: definitions for roles used in XAS profile
type: object
properties:
  '@type':
    type: array
    items:
      type: string
    minItems: 3
    uniqueItems: true
    allOf:
    - contains:
        const: schema:Event
      minContains: 1
    - contains:
        const: xas:AnalysisEvent
      minContains: 1
    - contains:
        const: prov:Activity
      minContains: 1
  'schema:identifier':
    anyOf:
    - type: string
    - $ref: '#/$defs/Identifier'
  'schema:startDate':
    type: string
  'prov:used':
    type: array
    items:
      $ref: '#/$defs/Instrument'
  'schema:additionalProperty':
    type: array
    description: add additional property propertyIDs:xas:edge_energy, calibration method, Instrument configuration,
      xas:installedOptions
    items:
      allOf:
      - $ref: '#/$defs/AdditionalProperty'
      - properties:
          'schema:propertyID':
            type: array
            minItems: 1
            items:
              anyOf:
              - $ref: ../../schemaorgProperties/additionalProperty/additionalPropertySchema.json#/$defs/propertyID_item
              - enum:
                - 'xas:edge_energy'
                - 'calibration method'
                - 'Instrument configuration'
                - 'xas:installedOptions'
  'schema:location':
    $ref: '#/$defs/Facility'
  'schema:mainEntity':
    $ref: '#/$defs/Sample'
$defs:
  Identifier:
    $ref: ../../schemaorgProperties/identifier/schema.yaml
  Sample:
    $ref: ../xasSample/schema.yaml
  AdditionalProperty:
    $ref: ../../schemaorgProperties/additionalProperty/schema.yaml
  Facility:
    $ref: ../xasFacility/schema.yaml
  Instrument:
    $ref: ../xasInstrument/schema.yaml