$schema: https://json-schema.org/draft/2020-12/schema
title: Other File Type
description: >-
  Files in other widely-used formats approved for submission to the Astromat Archive.
  Includes EMSA, OBJ, STL, XLSX, and Neptune Plus export formats.
type: object
properties:
  "@type":
    const:
      - "ada:otherFileType"
  componentType:
    anyOf:
      - type: object
        properties:
          "@type":
            enum:
              - "ada:other"
        required:
          - "@type"
      - $ref: ../detailSLS/schema.yaml
  "schema:encodingFormat":
    description: >-
      One of the approved non-standard file formats:
      'Spectral Data Exchange File (.emsa)'-->text/plain;
      '3D model file (.obj)'-->model/obj;
      'Standard Triangle Language (.stl)'-->model/stl;
      'Open XML workbook (.xlsx)'-->application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;
      'Neptune Plus export (.exp)'-->application/octet-stream
    enum:
      - "text/plain"
      - "model/obj"
      - "model/stl"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      - "application/octet-stream"
  formatDescription:
    type: string
    description: >-
      Free text explanation of file format, or a link to a publicly accessible
      specification for the format.
required:
  - "@type"
  - componentType
