---
$schema: https://json-schema.org/draft/2020-12/schema
title: Files Type
description: Properties for any file in an ADA product distribution. GeneralType provides info based on
  broad categories of file format (tabular, image, dataCube, document). Type constraints (e.g. DataDownload)
  are applied at the composition level in profiles.
allOf:
- $ref: ../schemaorgProperties/dataDownload.yaml
- type: object
  description: properties added for geochemical datasets
  properties:
    schema:additionalType:
      type: array
      description: other classifier for the file. ada componentTypes are specified in the specific file type schema attached by $refs
      items:
        type: string
    schema:description:
      type: string
    schema:size:
      type: object
      properties:
        '@type':
          const: schema:QuantitativeValue
        schema:value:
          type: integer
        schema:unitText:
          type: string
          default: byte
    schema:relatedLink:
      type: array
      description: 'Links between files in the product. Use schema:name for path to target in product, or use #id JSON-LD links. Used to link metadata files in bundle to the data or supplementary files they document.'
      items:
        type: object
        properties:
          '@type':
            type: string
            const: schema:LinkRole
          schema:linkRelationship:
            type: string
          schema:target:
            type: object
            properties:
              '@type':
                type: string
                const: schema:EntryPoint
              schema:encodingFormat:
                type: string
              schema:name:
                type: string
              schema:url:
                type: string
- anyOf:
  - $ref: ../image/imageSchema.json
  - $ref: ../imageMap/imageMapSchema.json
  - $ref: ../tabularData/tabularDataSchema.json
  - $ref: ../collection/collectionSchema.json
  - $ref: ../dataCube/dataCubeSchema.json
  - $ref: ../document/documentSchema.json
  - $ref: ../supDocImage/supDocImageSchema.json
  - $ref: ../otherFile/otherFileSchema.json
  - type: object
    properties:
      '@type':
        const:
        - Metadata
    required:
    - '@type'
  - type: object
    description: DataDownload distribution (archive or direct download without specific file type)
    properties:
      '@type':
        type: array
        contains:
          const: "schema:DataDownload"
    required:
      - '@type'