---
$schema: https://json-schema.org/draft/2020-12/schema
allOf:
- $ref: '#/$defs/CdifMandatory'
- type: object
  properties:
    schema:subjectOf:
      $ref: '#/$defs/XasSubject'
    prov:wasGeneratedBy:
      type: array
      items:
        type: object
        properties:
          prov:used:
            type: array
            description: 'array of instrument or instrument system components. The x-ray source type and
              probe,  and monochromator properties type, d-spacing and reflection plane are required '
            allOf:
            - contains:
                type: object
                properties:
                  '@type':
                    type: array
                    items:
                      type: string
                    minItems: 2
                    allOf:
                    - contains:
                        const: schema:Thing
                    - contains:
                        const: schema:Product
                  schema:additionalType:
                    const: nxs:BaseClass/NXsource
                  schema:additionalProperty:
                    type: array
                    minItems: 2
                    items:
                      $ref: '#/$defs/AdditionalProperty'
                    allOf:
                    - contains:
                        type: object
                        properties:
                          schema:propertyID:
                            type: array
                            contains:
                              const: nxs:Field/NXsource/type
                          schema:value:
                            type: string
                        required:
                        - schema:propertyID
                        - schema:value
                    - contains:
                        type: object
                        properties:
                          schema:propertyID:
                            type: array
                            contains:
                              const: nxs:Field/NXsource/probe
                          schema:name:
                            const: Probe
                          schema:value:
                            type: string
                        required:
                        - schema:name
                        - schema:propertyID
                        - schema:value
                required:
                - '@type'
                - schema:additionalType
                - schema:additionalProperty
            - contains:
                type: object
                properties:
                  '@type':
                    type: array
                    items:
                      type: string
                    minItems: 2
                    allOf:
                    - contains:
                        const: schema:Thing
                    - contains:
                        const: schema:Product
                  schema:additionalType:
                    const: nxs:BaseClass/NXmonochromator
                  schema:name:
                    type: string
                  schema:additionalProperty:
                    description: Require additional properties for monochromator, requires d-space, crystal
                      type, reflection plane.
                    type: array
                    minItems: 3
                    items:
                      $ref: '#/$defs/AdditionalProperty'
                    contains:
                      type: object
                      properties:
                        schema:propertyID:
                          type: array
                          contains:
                            const: nxs:Field/NXcrystal/type
                        schema:value:
                          type: string
                      required:
                      - schema:value
                      - schema:propertyID
                    allOf:
                    - contains:
                        type: object
                        properties:
                          schema:propertyID:
                            type: array
                            contains:
                              const: nxs:Field/NXcrystal/d_spacing
                          schema:value:
                            type: string
                          schema:unitText:
                            type: string
                        required:
                        - schema:propertyID
                        - schema:value
                        - schema:unitText
                    - contains:
                        type: object
                        properties:
                          schema:propertyID:
                            type: array
                            contains:
                              const: nxs:Field/NXcrystal/reflection
                          schema:value:
                            type: string
                        required:
                        - schema:value
                        - schema:propertyID
                required:
                - '@type'
                - schema:additionalType
                - schema:additionalProperty
          schema:mainEntity:
            $ref: '#/$defs/XasSample'
    schema:distribution:
      type: array
      items:
        $ref: '#/$defs/DataDownload'
      contains:
        type: object
        properties:
          '@type':
            type: array
            items:
              type: string
            minItems: 2
            allOf:
            - contains:
                const: schema:DataDownload
            - contains:
                const: cdi:PhysicalDataset
          dcterms:conformsTo:
            const: https://github.com/XraySpectroscopy/XAS-Data-Interchange/blob/master/specification/spec.md
        required:
        - '@type'
        - dcterms:conformsTo
    schema:measurementTechnique:
      type: array
      description: 'Require DefinedTerms for both: absorption edge (XDI dict) and target element (SWEET).'
      minItems: 2
      items:
        $ref: '#/$defs/DefinedTerm'
      allOf:
      - contains:
          type: object
          properties:
            schema:name:
              const: X-Ray Absorption Spectroscopy
            schema:termCode:
              const: XAS
            schema:identifier:
              const: http://purl.org/pan-science/PaNET/PaNET01196
            schema:inDefinedTermSet:
              const: http://purl.org/pan-science/PaNET/PaNET.owl
          required:
          - schema:name
          - schema:termCode
          - schema:identifier
          - schema:inDefinedTermSet
      - contains:
          type: object
          properties:
            schema:name:
              type: string
            schema:inDefinedTermSet:
              const: nxs:Field/NXxas/ENTRY/DATA/mode
          required:
          - schema:name
          - schema:inDefinedTermSet
    schema:keywords:
      type: array
      description: extends base CDIF keyword schema to require defined terms for the absorption edge and
        the target element for the analysis
      minItems: 2
      items:
        type: object
        properties:
          '@type':
            const: schema:DefinedTerm
          schema:name:
            type: string
          schema:identifier:
            type: string
          schema:inDefinedTermSet:
            type: string
            description: need to include this to tag what the keyword is about; we're using the keywords
              as soft-typed properties
        required:
        - '@type'
        - schema:name
        - schema:inDefinedTermSet
        additionalProperties: true
      allOf:
      - contains:
          type: object
          properties:
            schema:inDefinedTermSet:
              const: https://github.com/XraySpectroscopy/XAS-Data-Interchange/blob/master/specification/dictionary.md
          required:
          - schema:inDefinedTermSet
      - contains:
          type: object
          properties:
            schema:inDefinedTermSet:
              const: http://sweetontology.net/matrElement
          required:
          - schema:inDefinedTermSet
$defs:
  CdifMandatory:
    $ref: ../../schemaorgProperties/cdifMandatory/cdifMandatorySchema.json
  DefinedTerm:
    $ref: ../../schemaorgProperties/definedTerm/definedTermSchema.json
  AdditionalProperty:
    $ref: ../../schemaorgProperties/additionalProperty/additionalPropertySchema.json
  DataDownload:
    $ref: ../../schemaorgProperties/dataDownload/dataDownloadSchema.json
  XasSample:
    $ref: ../xasSample/xasSampleSchema.json
  XasSubject:
    $ref: ../xasSubject/XasSubjectSchema.json