$schema: https://json-schema.org/draft/2020-12/schema
title: PSFD Instrument Detail
description: Point Spread Function Data with image names and conditions
type: object
properties:
  "@type":
    const: "ada:PSFDTabular"
  imageName:
    $ref: ../stringArray/schema.yaml
  imageViewingConditions:
    type: string
