$schema: https://json-schema.org/draft/2020-12/schema
title: ADA VNMIR Product Profile
description: >-
  Technique-specific profile for Very-Near Mid-Infrared (VNMIR/FTIR) spectroscopy
  products. Extends the base ADA product profile with constraints on valid VNMIR
  component types and vnmir_detail requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a VNMIR product type identifier.
        contains:
          enum:
            - "ada:VNMIRPoint"
            - "ada:VNMIROverviewImage"
            - "ada:VNMIRSpectralMap"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:VNMIRSpectralPoint"
                        - "ada:VNMIROverviewImage"
                        - "ada:VNMIRSpectralMap"
                        - "ada:VNMIRSpectraPlot"
                        - "ada:analysisLocation"
                        - "ada:instrumentMetadata"
                        - "ada:methodDescription"
                  fileDetail:
                    anyOf:
                      - $ref: ../../adaProperties/tabularData/schema.yaml
                      - $ref: ../../adaProperties/imageMap/schema.yaml
                      - $ref: ../../adaProperties/dataCube/schema.yaml
                      - $ref: ../../adaProperties/supDocImage/schema.yaml
                      - $ref: ../../adaProperties/document/schema.yaml
