$schema: https://json-schema.org/draft/2020-12/schema
title: ARGT Instrument Detail
description: ARGT (Argon) document type with phase and isotope analysis
type: object
properties:
  "@type":
    const: "ada:ARGTDocument"
  phaseAnalyzed:
    type: string
  isotopeType:
    type: string
