---
$schema: https://json-schema.org/draft/2020-12/schema
description: "Spatial Extent description for CDIF discovery profile.  Note required prefix declaration\
  \ for geoSparql ( http://www.opengis.net/ont/geosparql#) and OGC simple features\
  \ (sf: http://www.opengis.net/ont/sf#)"
type: object
properties:
  '@type':
    type: string
    const: schema:Place
    default: schema:Place
  'schema:name':
    description: multiple place names or DefinedTerms that have a place name and URI for the location
    type: array
    items:
      anyOf:
      - type: string
      - $ref: '#/$defs/DefinedTerm'
  'schema:geo':
    description: Either a bounding box or a point location.
    anyOf:
    - type: object
      description: A point location. Point locations are recommended for data that is associated with
        specific sample locations, particularly if these are widely spaced such that an enclosing bounding
        box would be a misleading representation of the spatial location. Be aware that some client applications
        might only index or display bounding box extents or a single point location.
      properties:
        '@type':
          type: string
          const: schema:GeoCoordinates
          default: schema:GeoCoordinates
        'schema:latitude':
          type: number
        'schema:longitude':
          type: number
      required:
      - '@type'
      - 'schema:latitude'
      - 'schema:longitude'
    - type: object
      description: A schema:GeoShape bounding box. The geometry is described with a set of latitude/longitude
        pairs (in that order).The documentation for schema:GeoShape states 'Either whitespace or commas
        can be used to separate latitude and longitude; whitespace should be used when writing a list
        of several such points.'
      properties:
        '@type':
          type: string
          const: schema:GeoShape
          default: schema:GeoShape
        'schema:box':
          type: string
          description: A GeoShape box defines an area on the surface of the earth defined by point locations
            of the southwest corner and northeast corner of the rectangle in latitude-longitude coordinates.
            A space should be used to separate the latitude and longitude values. The two corner coordinate
            points are separated by a space. 'East longitude' means positive longitude values are east
            of the prime (Greenwich) meridian.
      required:
      - '@type'
      - 'schema:box'
    - type: object
      description: A schema:GeoShape curvilinear trace, for resource related to a linear trace like a
        ship track or airplane flight line
      properties:
        '@type':
          type: string
          const: schema:GeoShape
          default: schema:GeoShape
        'schema:line':
          type: string
          description: 'A GeoShape box defines a curvilinear geometry as a string of latitude-longitude
            coordinates. A space should be used to separate the latitude and longitude values. The coordinate
            point pairs are also separated by a space. ''East longitude'' means positive longitude values
            are east of the prime (Greenwich) meridian. e.g. ''39.33 120.77 40.44 123.96 41.00 121.34'' '
      required:
      - '@type'
      - schema:line
  'geosparql:hasGeometry':
    type: object
    description: Optional geographic extent using wkt geometry, see Ocean InfoHub (https://book.oceaninfohub.org/thematics/spatial/README.html#simple-geosparql-wkt).
      Other geometry schemes might be specified in a specific domain profile, e.g. for atmospheric, subsurface
      data, or local coordinate systems. NOTE that the location specified here should be the same as the
      schema.org point or contained within the specified bounding box.
    properties:
      '@type':
        type: string
        description: 'MUST be sf: (<http://www.opengis.net/ont/sf#>) SimpleFeature geometry type. See
          https://opengeospatial.github.io/ogc-geosparql/geosparql11/sf_geometries.ttl'
      'geosparql:asWKT':
        type: object
        properties:
          '@type':
            type: string
            const: geosparql:wktLiteral
          '@value':
            type: string
            description: a WKT geometry description string, e.g. 'POINT(-76 -18)'
      'geosparql:crs':
        type: object
        properties:
          '@id':
            type: string
            description: identifier string for coordinate reference system, e.g., 'CRS84'
$defs:
  DefinedTerm:
    $ref: ../definedTerm/schema.yaml