$schema: https://json-schema.org/draft/2020-12/schema
title: ADA L2MS Product Profile
description: >-
  Technique-specific profile for Two-Step Laser Mass Spectrometry (L2MS) products.
  Extends the base ADA product profile with constraints on valid L2MS component
  types and detailL2MS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a L2MS product type identifier.
        contains:
          enum:
            - "ada:L2MSCube"
            - "ada:L2MSOverviewImage"
            - "Microprobe Two-Step Laser Mass Spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:L2MSCube"
                        - "ada:L2MSOverviewImage"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
