$schema: https://json-schema.org/draft/2020-12/schema
title: ADA L2MS Product Profile
description: >-
  Technique-specific profile for Two-Step Laser Mass Spectrometry (L2MS) products.
  Extends the base ADA product profile with constraints on valid L2MS component
  types and detailL2MS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a L2MS product type identifier.
        contains:
          enum:
            - "Microprobe Two-Step Laser Mass Spectrometry (L2MS)"
            - "Microprobe Two-Step Laser Mass Spectrometry"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:L2MSCube"
                          - "ada:L2MSOverviewImage"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
