$schema: https://json-schema.org/draft/2020-12/schema
title: ADA QRIS Product Profile
description: >-
  Technique-specific profile for Quantitative Reflectance Imaging Spectroscopy (QRIS) products.
  Extends the base ADA product profile with constraints on valid QRIS component
  types and detailQRIS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a QRIS product type identifier.
        contains:
          enum:
            - "Quantitative Reflective Imaging System (QRIS) Calibrated"
            - "Quantitative Reflective Imaging System (QRIS) Raw"
            - "Quantitative Reflective Imaging System"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:QRISCalibratedCollection"
                          - "ada:QRISRawCollection"
                          - "ada:QRISCalibrationFile"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
