$schema: https://json-schema.org/draft/2020-12/schema
title: ADA QRIS Product Profile
description: >-
  Technique-specific profile for Quantitative Reflectance Imaging Spectroscopy (QRIS) products.
  Extends the base ADA product profile with constraints on valid QRIS component
  types and detailQRIS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a QRIS product type identifier.
        contains:
          enum:
            - "ada:QRISCalibratedCollection"
            - "ada:QRISRawCollection"
            - "ada:QRISCalibrationFile"
            - "Quantitative Reflectance Imaging System"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:QRISCalibratedCollection"
                          - "ada:QRISRawCollection"
                          - "ada:QRISCalibrationFile"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:calibrationFile"
