---
$schema: https://json-schema.org/draft/2020-12/schema
description: Extends cdif variableMeasured with properties for DDI-CDI InstanceVariable
type: object
properties:
  '@type':
    type: array
    description: require additional type besided schema:PropertyValue required by CDIF variableMeasured,
      so min items should add up to 2 (we'll see if this works....)
    items:
      type: string
      enum:
        - schema:PropertyValue
        - cdi:InstanceVariable
    minItems: 2
  'cdi:identifier':
    type: string
  'cdi:physicalDataType':
    type: array
    items:
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a skos concept for the data type
      - $ref: '#/$defs/DefinedTerm'
    description: identifier or name for the data type concept.
  'cdi:intendedDataType':
    type: string
    description: The intended data type for values of this variable, from DDI-CDI RepresentedVariable.hasIntendedDataType.
      Recommended values are XML Schema datatypes (e.g. https://www.w3.org/TR/xmlschema-2/#decimal).
  'cdi:role':
    type: string
    description: Specifies the relation of the variable to the data structure, corresponding to
      DDI-CDI DataStructureComponent subtypes. Values should be one of {MeasureComponent,
      AttributeComponent, DimensionComponent}.
  'cdi:describedUnitOfMeasure':
    description: A structured unit of measure from a controlled vocabulary, from DDI-CDI
      RepresentedVariable.describedUnitOfMeasure.
    $ref: '#/$defs/DefinedTerm'
  'cdi:simpleUnitOfMeasure':
    anyOf:
    - type: string
    - type: object
      properties:
        '@id':
          type: string
          description: reference to a skos concept for the data type
    - $ref: '#/$defs/DefinedTerm'
  'cdi:uses':
    type: array
    items:
      anyOf:
      - type: string
      - type: object
        properties:
          '@id':
            type: string
            description: reference to a skos concept for the property
      - $ref: '#/$defs/DefinedTerm'
    description: Essentially the same as schema:propertyID. References to concepts that this
      variable measures or represents.
  'cdi:name':
    type: string
    description: DDI-CDI Concept.name. The name of this variable in the DDI-CDI model.
  'cdi:displayLabel':
    type: string
    description: DDI-CDI Concept.displayLabel. A human-readable label for display purposes.
$defs:
  DefinedTerm:
    $ref: ../../schemaorgProperties/definedTerm/schema.yaml
allOf:
- required:
  - '@type'
  - cdi:physicalDataType
- $ref: ../../schemaorgProperties/variableMeasured/schema.yaml