$schema: https://json-schema.org/draft/2020-12/schema
title: ADA SLS Product Profile
description: >-
  Technique-specific profile for Structured Light Scanning (SLS) products.
  Extends the base ADA product profile with constraints on valid SLS component
  types and detailSLS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a SLS product type identifier.
        contains:
          enum:
            - "ada:SLSShapeModel"
            - "ada:SLSPartialScan"
            - "ada:ShapeModelImage"
            - "Structured Light Scanning"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  "schema:additionalType":
                    items:
                      enum:
                        - "ada:SLSShapeModel"
                        - "ada:SLSPartialScan"
                        - "ada:ShapeModelImage"
                        - "ada:analysisLocation"
                        - "ada:methodDescription"
                        - "ada:instrumentMetadata"
                        - "ada:calibrationFile"
