$schema: https://json-schema.org/draft/2020-12/schema
title: ADA SLS Product Profile
description: >-
  Technique-specific profile for Structured Light Scanning (SLS) products.
  Extends the base ADA product profile with constraints on valid SLS component
  types and detailSLS requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a SLS product type identifier.
        contains:
          enum:
            - "SLSIndividualScanCollection"
            - "Structured Light Scanning (SLS) Shape Model"
            - "Structured Light Scanning"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:SLSShapeModel"
                          - "ada:SLSPartialScan"
                          - "ada:ShapeModelImage"
                          - "ada:analysisLocation"
                          - "ada:annotatedImage"
                          - "ada:areaOfInterest"
                          - "ada:basemap"
                          - "ada:calibrationFile"
                          - "ada:code"
                          - "ada:contextPhotography"
                          - "ada:contextVideo"
                          - "ada:inputFile"
                          - "ada:instrumentMetadata"
                          - "ada:logFile"
                          - "ada:methodDescription"
                          - "ada:other"
                          - "ada:plot"
                          - "ada:processingMethod"
                          - "ada:quickLook"
                          - "ada:report"
                          - "ada:samplePreparation"
                          - "ada:shapefile"
                          - "ada:supplementalBasemap"
                          - "ada:supplementaryImage"
                          - "ada:worldFile"
