$schema: https://json-schema.org/draft/2020-12/schema
title: ADA LIT Product Profile
description: >-
  Technique-specific profile for Lock-In Thermography (LIT) products.
  Extends the base ADA product profile with constraints on valid LIT component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a LIT product type identifier.
        contains:
          enum:
            - "Lock-In Thermography (LIT) image"
            - "Lock-In Thermography (LIT) Collection"
            - "Lock-In Thermography"
      "schema:distribution":
        items:
          properties:
            "schema:hasPart":
              items:
                properties:
                  componentType:
                    properties:
                      "@type":
                        enum:
                          - "ada:LITImage"
                          - "ada:LIT2DDataCollection"
                          - "ada:LITPolarDataCollection"
                          - "ada:analysisLocation"
                          - "ada:methodDescription"
                          - "ada:instrumentMetadata"
                          - "ada:other"
                          - "ada:calibrationFile"
